version: '3.8'

# This docker-compose will help you spawn all dependencies for examples/server.py

services:
  # Jaeger is needed to ensure you have somewhere to store all emitted metrics + provides nice UI
  jaeger:
    image: jaegertracing/all-in-one:1.57
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "6831:6831/udp"  # Thrift compact
      - "6832:6832/udp"  # Thrift binary
      - "5778:5778"      # Agent HTTP
      - "16686:16686"    # Jaeger UI
      - "4317:4317"      # OTLP gRPC
      - "4318:4318"      # OTLP HTTP
      - "14250:14250"    # OTLP HTTP (alternative)
      - "14268:14268"    # Jaeger HTTP thrift
      - "14269:14269"    # Jaeger gRPC
      - "9411:9411"      # Zipkin
  
  # Redis is one of the instrumented libraries that is tested inside examples/server.py
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "always"]
    restart: always
  
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
