version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "6831:6831/udp"  # Thrift compact
      - "6832:6832/udp"  # Thrift binary
      - "5778:5778"      # Agent HTTP
      - "16686:16686"    # Jaeger UI
      - "4317:4317"      # OTLP gRPC
      - "4318:4318"      # OTLP HTTP
      - "14250:14250"    # OTLP HTTP (alternative)
      - "14268:14268"    # Jaeger HTTP thrift
      - "14269:14269"    # Jaeger gRPC
      - "9411:9411"      # Zipkin
