name: CaptureFlow Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  server_build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.11 ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install server dependencies
      run: |
        python -m pip install --upgrade pip
        cd serverside/
        pip install -r requirements-dev.txt

    - name: Run server pytest
      run: |
        cd serverside/
        pytest

    - name: Check server code with black
      run: |
        cd serverside/
        black --check .

    - name: Check server code with isort
      run: |
        cd serverside/
        isort --check-only .

  client_build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.11 ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install client dependencies
      run: |
        python -m pip install --upgrade pip
        cd clientside/
        pip install -r requirements-dev.txt

    - name: Run client pytest
      run: |
        cd clientside/
        pytest

    - name: Check client code with black
      run: |
        cd clientside/
        black --check .

    - name: Check client code with isort
      run: |
        cd clientside/
        isort --check-only .
